//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriBankasi.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeriBankasi.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string btnadd {
            get {
                return ResourceManager.GetString("btnadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string btncancel {
            get {
                return ResourceManager.GetString("btncancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string btnok {
            get {
                return ResourceManager.GetString("btnok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem iptal edildi.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük dosyasını kontrol edin : .
        /// </summary>
        internal static string checkerrorlog {
            get {
                return ResourceManager.GetString("checkerrorlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silmek istediğinize emin misiniz?.
        /// </summary>
        internal static string deletemessage {
            get {
                return ResourceManager.GetString("deletemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya silindi.
        /// </summary>
        internal static string deletesuccess {
            get {
                return ResourceManager.GetString("deletesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkmak istediğinize emin misiniz?.
        /// </summary>
        internal static string exitques {
            get {
                return ResourceManager.GetString("exitques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarısız.
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string kad {
            get {
                return ResourceManager.GetString("kad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henüz dil desteklenmiyor..
        /// </summary>
        internal static string lngnotsupport {
            get {
                return ResourceManager.GetString("lngnotsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Yapılıyor....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni belge.
        /// </summary>
        internal static string newDocument {
            get {
                return ResourceManager.GetString("newDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni klasör.
        /// </summary>
        internal static string newFolder {
            get {
                return ResourceManager.GetString("newFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boş olamaz.
        /// </summary>
        internal static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili nesne yok.
        /// </summary>
        internal static string objectnotselected {
            get {
                return ResourceManager.GetString("objectnotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana dizin.
        /// </summary>
        internal static string parentdirectory {
            get {
                return ResourceManager.GetString("parentdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola koruması ekle.
        /// </summary>
        internal static string passtool {
            get {
                return ResourceManager.GetString("passtool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRR Veri Deposu.
        /// </summary>
        internal static string progname {
            get {
                return ResourceManager.GetString("progname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma esnasında parolayı hatırla.
        /// </summary>
        internal static string pwhatirla {
            get {
                return ResourceManager.GetString("pwhatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola korumasını kaldır.
        /// </summary>
        internal static string removepass {
            get {
                return ResourceManager.GetString("removepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden adlandır.
        /// </summary>
        internal static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarısız.
        /// </summary>
        internal static string savefail {
            get {
                return ResourceManager.GetString("savefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarılı.
        /// </summary>
        internal static string savesuccess {
            get {
                return ResourceManager.GetString("savesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst dizin seçin.
        /// </summary>
        internal static string topdirectory {
            get {
                return ResourceManager.GetString("topdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinmeyen hata.
        /// </summary>
        internal static string unknownerror {
            get {
                return ResourceManager.GetString("unknownerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış şifre!.
        /// </summary>
        internal static string wrngpsw {
            get {
                return ResourceManager.GetString("wrngpsw", resourceCulture);
            }
        }
    }
}
